# safelist
branches:
  only:
  - master

#variables
env:
  global:
  - 'USER=fmc'
  - 'PWD=fmc'

addons:
  apt:
    packages:
    - lftp

language: java
jdk: openjdk8

script:
- gradle build

after_success:
- ls ./build/libs
- JARFILE=`ls ./build/libs`;export JARFILE
- lftp -c "open -u ${USER},${PWD} fais-mes-courses.fr; put -O /home/fmc/env/bin/ ./build/libs/${JARFILE}"