# safelist
branches:
  only:
  - master

#variables
env:
  global:
  - 'USER=fmc'
  - 'PWD=fmc'

language: java
jdk: openjdk8

script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew build


after_success:
- ls ./build/libs
- lftp -c "open -u ${USER},${PWD} fais-mes-courses.fr; put -O /home/fmc/env/bin/ ./build/libs/java-back-0.0.1-SNAPSHOT.jar"